### ISSUE TITLE
How to use this project as a dependency using Stack?

### ISSUE THREAD

**Issue by listx** [awakesecurity/gRPC-haskell#164]
The README explains how to use this project with Nix + Cabal.

But how are you supposed to use it with Stack? Am I supposed to clone this repo as a submodule and then reference it locally, or something? I noticed in https://github.com/awakesecurity/gRPC-haskell/pull/155 that GHC 9.2.8 was supported but on Stack, and was wondering how to take advantage of that for my project. Thanks

**Comment by listx** [comment]
I found https://stackoverflow.com/a/59233321/437583. Will reopen this issue if that doesn't work (doubtful). Cheers

**Comment by ixmatus** [comment]
Rather than referencing local paths, I recommend referencing the git revision you want directly in the stack yaml:

```
packages:
- location:
    git: git@github.com:awakesecurity/gRPC-haskell.git
    commit: <commit_hash>
```
