### ISSUE TITLE
stack build error with grpc_haskell.h file

### ISSUE THREAD

**Issue by mut0u** [awakesecurity/gRPC-haskell#49]
I clone the grpc and change the version to 1.0.1 to build grcp lib.
When I build the gRPC-haskell project the error is:

```
    Configuring grpc-haskell-core-0.0.0.0...
    Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2: Bad header file:
    include/grpc_haskell.h
    The header file contains a compile error. You can re-run configure with the
    verbosity flag -v3 to see the error messages from the C compiler.
```
And I have no idea how to fix it .

**Comment by ixmatus** [comment]
Can you try using GRPC 1.2.0? After I closed your last ticket, I read through our README and realized the instructions to build with stack mention using GRPC version 1.0.1

If using 1.2.0 fixes this issue then we just need to update the README for accuracy.

**Comment by mut0u** [comment]
I found that the project dependent grpc v1.2.0 version .

**Comment by mut0u** [comment]
I found I have to use GRPC v1.2.0  too.  
I build a grpc demo with it, and my stack.yml config like this:

```
extra-deps:
- git: https://github.com/awakesecurity/gRPC-haskell.git
  commit: 5fd44880da343343a7a25ff0bc42e07c044432f7
  subdirs:
  - core
- git: https://github.com/awakesecurity/proto3-suite.git
  commit: 11fc7cce58e754d1495dabe65dbfe62fb23bb38f

- git: https://github.com/awakesecurity/proto3-wire.git
  commit: 23b6ed40288e36b5849d74c86a5cd0fa7548f043

```

when I run `stack build` , it raise a error 

```
    Preprocessing library for proto3-suite-0.1.0.0..
    Building library for proto3-suite-0.1.0.0..
    [ 1 of 13] Compiling Proto3.Suite.DotProto.AST ( src/Proto3/Suite/DotProto/AST.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.0.1.0/build/Proto3/Suite/DotProto/AST.o )
    
   demo-grpc/.stack-work/downloaded/XJwrjlKl8Cc8/src/Proto3/Suite/DotProto/AST.hs:391:22: error:
        • No instance for (Arbitrary Natural)
            arising from a use of ‘arbitrary’
        • In a stmt of a 'do' block: natural <- arbitrary
          In the expression:
            do natural <- arbitrary
               return (fromIntegral (natural :: Natural))
          In an equation for ‘arbitraryFieldNumber’:
              arbitraryFieldNumber
                = do natural <- arbitrary
                     return (fromIntegral (natural :: Natural))
        |
    391 |           natural <- arbitrary
        |                      ^^^^^^^^^
    

```
But I can buid the `proto3-suite` project
